Repository apecloud/ApeRAG, pull requests merged in 2025-07, with the labels that each got.

#1006 feat: add env for deploy
  aperag/config.py
  aperag/graph/lightrag_manager.py
  config/settings.py
  deploy/aperag/templates/aperag-secret.yaml
  deploy/aperag/templates/api-deployment.yaml
  deploy/aperag/templates/celerybeat-deployment.yaml
  deploy/aperag/templates/celeryworker-deployment.yaml
  deploy/aperag/templates/flower-deployment.yaml
  deploy/aperag/values.yaml
  envs/env.template
Labels: size/L

#1007 Feature/fix build docker image
  Dockerfile
Labels: size/L

#1010 feat: add DEFAULT_ENTITY_TYPES
  aperag/graph/lightrag/prompt.py
  deploy/aperag/values.yaml
  scripts/start-celery-worker.sh
Labels: size/M

#1011 feat: remove neo4j for dev
  Makefile
  README.md
  README_zh.md
  docker-compose.yml
  docs/build-docker-image.md
  docs/design/ApeRAG_Document_Processing_Flow-zh.md
  docs/design/ApeRAG_Document_Processing_Flow.md
  docs/design/Connected_Components_Optimization.md
  docs/design/Graph_Indexing_Concurrency_Optimization.md
  docs/design/LightRAG_Entity_Extraction_and_Merging.md
  docs/design/indexing_architecture.md
  docs/design/indexing_architecture_zh.md
  docs/development-guide.md
  docs/images/collection-page.png
  docs/reference/HOW-TO-DEBUG-zh.md
  docs/reference/HOW-TO-DEBUG.md
  envs/docker.env.overrides
Labels: size/XL

#1019 feat: add jina llm provider
  aperag/migration/sql/model_configs_init.sql
  models/generate_model_configs.py
Labels: size/L

#1013 feat: update README & docker compose
  Makefile
Labels: size/XS

#1021 feat: update default version
  Makefile
  README.md
  aperag/migration/sql/extensions_init.sql
  aperag/migration/versions/20250630123213-495840dd6ff9.py
  aperag/migration/versions/20250630151946-97d64d3fe985.py
  aperag/migration/versions/20250703133046-db9c88848f52.py
  aperag/migration/versions/20250703133208-0b274fcc91e2.py
  aperag/migration/versions/20250703133304-b598e645b2ba.py
  deploy/aperag/values.yaml
  docker-compose.yml
  docs/development-guide.md
Labels: size/XXL

#1016 feat: InActive to Active State Change Does Not Auto-Refresh on Frontend
  frontend/src/pages/collections/index.tsx
Labels: size/M

#1033 feat: enhance user role handling in audit and invitation views
  aperag/views/audit.py
  aperag/views/auth.py
Labels: size/S

#1035 fix: audit log access control based on user roles
  aperag/views/audit.py
Labels: size/XS

#1037 feat: graph
  frontend/deploy/startup.sh
  frontend/package.json
  frontend/src/global.less
  frontend/src/pages/collections/$collectionId/graphs.tsx
  frontend/yarn.lock
Labels: size/L

#1026 feat: support chunk visualization
  aperag/api/components/schemas/collection.yaml
  aperag/api/components/schemas/document.yaml
  aperag/api/openapi.yaml
  aperag/api/paths/collections.yaml
  aperag/index/vector_index.py
  aperag/schema/view_models.py
  aperag/service/document_service.py
  aperag/tasks/utils.py
  aperag/views/auth.py
  aperag/views/main.py
  frontend/package.json
  frontend/src/api/apis/default-api.ts
  frontend/src/api/models/collection-config.ts
  frontend/src/api/models/document-preview-chunks-inner.ts
  frontend/src/api/models/document-preview.ts
  frontend/src/api/models/index.ts
  frontend/src/api/models/parser-config.ts
  frontend/src/api/openapi.merged.yaml
  frontend/src/components/ChunkViewer.module.css
  frontend/src/components/ChunkViewer.tsx
  frontend/src/components/index.ts
  frontend/src/locales/en-US.ts
  frontend/src/locales/zh-CN.ts
  frontend/src/pages/collections/$collectionId/documents.tsx
  frontend/src/types/index.d.ts
  frontend/yarn.lock
Labels: size/XXL

#1038 Bugfix/graph
  frontend/src/global.less
  frontend/src/pages/collections/$collectionId/graphs.tsx
  frontend/src/pages/collections/index.tsx
  frontend/yarn.lock
Labels: size/L

#1041 fix: remove ingress annotations
  deploy/aperag/templates/ingress.yaml
  deploy/aperag/values.yaml
Labels: size/XS

#1036 chore: update helm and docker-compose image version
  deploy/aperag/README.md
  deploy/aperag/values.yaml
  docker-compose.yml
Labels: size/S

#1043 Feature/add agent
  aperag/agent/__init__.py
  aperag/agent/rag_agent.py
  aperag/mcp/server.py
  pyproject.toml
  uv.lock
Labels: size/XXL

#1044 feat: refine mcp
  README-zh.md
  README.md
  aperag/mcp/server.py
Labels: size/L

#1046 chore: update doc-ray version
  aperag/docparser/docray_parser.py
  aperag/service/document_service.py
  deploy/aperag/values.yaml
  docker-compose.yml
Labels: size/S

#1047 chore: add check button for MinerU API Token
  aperag/api/paths/collections.yaml
  aperag/schema/view_models.py
  aperag/service/collection_service.py
  aperag/views/main.py
  frontend/src/api/openapi.merged.yaml
  frontend/src/locales/en-US/collection.ts
  frontend/src/locales/zh-CN/collection.ts
  frontend/src/pages/collections/_form/index.tsx
Labels: size/L

#1054 feat: enhance document parsing task and update deployment strategies
  config/celery_tasks.py
  deploy/aperag/templates/celerybeat-deployment.yaml
  deploy/aperag/templates/celeryworker-deployment.yaml
  deploy/aperag/templates/flower-deployment.yaml
Labels: size/S

#1056 Fix/build frontend
  .github/workflows/release-image.yml
  Makefile
Labels: size/S

#1058 chore: add revisionHistoryLimit to deployment templates for consistency
  deploy/aperag/templates/api-deployment.yaml
  deploy/aperag/templates/celerybeat-deployment.yaml
  deploy/aperag/templates/celeryworker-deployment.yaml
  deploy/aperag/templates/docray.yaml
  deploy/aperag/templates/flower-deployment.yaml
  deploy/aperag/templates/frontend-deployment.yaml
Labels: size/XS

#1059 fix: polling collection
  frontend/src/pages/collections/$collectionId/_layout.tsx
  frontend/src/pages/collections/index.tsx
Labels: size/M

#1060 fix: global var disbaled in flow
  frontend/src/pages/bots/$botId/flow/_nodes/_node_llm.tsx
  frontend/src/pages/bots/$botId/flow/_nodes/_node_vector_search.tsx
  frontend/src/pages/collections/$collectionId/_layout.tsx
  frontend/src/pages/collections/index.tsx
Labels: size/S

#1062 fix: update FlowEvent initialization and logging to include node_type
  aperag/flow/engine.py
  aperag/flow/runners/llm.py
  aperag/utils/history.py
Labels: size/S

#1070 feat: support graph index node merge
  aperag/api/components/schemas/graph.yaml
  aperag/api/openapi.yaml
  aperag/api/paths/collections.yaml
  aperag/db/models.py
  aperag/exceptions.py
  aperag/graph/lightrag/lightrag.py
  aperag/graph/lightrag/prompt.py
  aperag/migration/versions/20250709200611-add_index_audit_resource.py
  aperag/schema/view_models.py
  aperag/service/graph_service.py
  aperag/views/main.py
  frontend/src/api/apis/graph-api.ts
  frontend/src/api/models/index.ts
  frontend/src/api/models/node-merge-request-target-entity-data.ts
  frontend/src/api/models/node-merge-request.ts
  frontend/src/api/models/node-merge-response-target-entity-data.ts
  frontend/src/api/models/node-merge-response.ts
  frontend/src/api/openapi.merged.yaml
Labels: size/XXL

#1075 Bugfix/graph
  frontend/package.json
  frontend/src/pages/agent/index.less
  frontend/src/pages/agent/index.tsx
  frontend/src/pages/collections/$collectionId/graphs/NodeDetail.tsx
  frontend/src/pages/collections/$collectionId/graphs/index.tsx
  frontend/yarn.lock
Labels: size/XL

#1079 chore: release nightly
  .github/workflows/release-image.yml
  .github/workflows/release-version.yml
Labels: size/M

#1080 chore: release nightly chart send message
  .github/workflows/release-chart.yml
  .github/workflows/release-image.yml
Labels: size/XS

#1085 feat: update readme kg
  README-zh.md
  README.md
  docs/images/HarryPotterKG.png
Labels: size/S

#1089 fix: resolve a flood of console warnings
  aperag/flow/engine.py
  aperag/index/fulltext_index.py
  aperag/schema/utils.py
  aperag/service/collection_service.py
  aperag/utils/audit_decorator.py
  aperag/vectorstore/qdrant_connector.py
Labels: size/M

#1090 Feature/merge nodes suggestion
  aperag/api/components/schemas/graph.yaml
  aperag/db/models.py
  aperag/db/ops.py
  aperag/db/repositories/merge_suggestion.py
  aperag/graph/lightrag/lightrag.py
  aperag/migration/versions/20250711123338-694591d5df94.py
  aperag/schema/view_models.py
  aperag/service/graph_service.py
  aperag/views/main.py
  frontend/src/api/models/index.ts
  frontend/src/api/models/merge-suggestion-entity.ts
  frontend/src/api/models/merge-suggestion-item.ts
  frontend/src/api/models/merge-suggestion.ts
  frontend/src/api/models/merge-suggestions-request.ts
  frontend/src/api/models/merge-suggestions-response.ts
  frontend/src/api/models/node-merge-request.ts
  frontend/src/api/models/node-merge-response.ts
  frontend/src/api/models/target-entity-data-request.ts
  frontend/src/api/models/target-entity-data-response.ts
  frontend/src/api/openapi.merged.yaml
Labels: size/XXL

#1092 feat: refine node merge
  aperag/api/components/schemas/graph.yaml
  aperag/api/openapi.yaml
  aperag/api/paths/collections.yaml
  aperag/db/repositories/merge_suggestion.py
  aperag/graph/lightrag/lightrag.py
  aperag/migration/versions/20250711123338-694591d5df94.py
  aperag/schema/view_models.py
  aperag/service/graph_service.py
  aperag/views/main.py
  frontend/src/api/apis/graph-api.ts
  frontend/src/api/models/index.ts
  frontend/src/api/models/node-merge-request.ts
  frontend/src/api/models/suggestion-action-request.ts
  frontend/src/api/models/suggestion-action-response.ts
  frontend/src/api/openapi.merged.yaml
  tests/unit_test/test_graph_service.py
Labels: size/XXL

#1104 feat: add liveness and readiness probes for API and Celery worker
  deploy/aperag/templates/api-deployment.yaml
  deploy/aperag/templates/celeryworker-deployment.yaml
  deploy/aperag/values.yaml
Labels: size/M

#1105 feat: centralize dynamic env var construction in config.py, remove composite vars from .env
  aperag/config.py
  envs/env.template
  scripts/entrypoint.sh
  scripts/start-celery-flower.sh
Labels: size/L

#1106 chore: remove useless code
  aperag/config.py
  aperag/index/vector_index.py
  aperag/tasks/collection.py
  config/flowerconfig.py
  config/urls.py
  config/vector_db.py
  config/wsgi.py
Labels: size/L

#1108 Chore/node merge
  aperag/app.py
  aperag/config.py
  aperag/index/vector_index.py
  aperag/tasks/collection.py
  aperag/views/auth.py
  aperag/views/test.py
  frontend/src/components/ChunkViewer.tsx
  frontend/src/locales/en-US/collection.ts
  frontend/src/locales/en-US/models.ts
  frontend/src/locales/zh-CN/collection.ts
  frontend/src/locales/zh-CN/models.ts
  frontend/src/pages/agent/index.less
  frontend/src/pages/agent/index.tsx
  frontend/src/pages/collections/$collectionId/graphs/MergeSuggestion.tsx
  frontend/src/pages/collections/$collectionId/graphs/NodeDetail.tsx
  frontend/src/pages/collections/$collectionId/graphs/index.tsx
  frontend/src/pages/settings/modelConfiguration.tsx
  tests/e2e_test/conftest.py
Labels: size/XXL

#1110 feat: update image
  deploy/aperag/README.md
  deploy/aperag/values.yaml
  docker-compose.yml
Labels: size/S

#1112 feat: fix compose env
  envs/docker.env.overrides
Labels: size/XS

#1118 feat: remove default assignees
  .github/ISSUE_TEMPLATE/bug_report.md
  .github/ISSUE_TEMPLATE/feature_request.md
  .github/ISSUE_TEMPLATE/improvement-request.md
Labels: size/XS

#1128 feat: fix concurrent suggestion
  aperag/service/graph_service.py
Labels: size/L

#1140 fix: specify mimetype for *.mjs files
  frontend/deploy/startup.sh
Labels: size/M

#1155 refactor: limit list_collections to safe fields for LLM usage
  aperag/mcp/server.py
Labels: size/M

#1073 feat: add vision index
  aperag/api/components/schemas/chat.yaml
  aperag/api/components/schemas/collection.yaml
  aperag/api/components/schemas/document.yaml
  aperag/db/models.py
  aperag/db/repositories/document.py
  aperag/db/repositories/llm_provider.py
  aperag/flow/runners/graph_search.py
  aperag/flow/runners/llm.py
  aperag/flow/runners/vector_search.py
  aperag/graph/lightrag/lightrag.py
  aperag/graph/lightrag_manager.py
  aperag/index/base.py
  aperag/index/document_parser.py
  aperag/index/fulltext_index.py
  aperag/index/manager.py
  aperag/index/summary_index.py
  aperag/index/vector_index.py
  aperag/index/vision_index.py
  aperag/llm/completion/base_completion.py
  aperag/llm/completion/completion_service.py
  aperag/llm/embed/base_embedding.py
  aperag/llm/embed/embedding_service.py
  aperag/mcp/server.py
  aperag/migration/sql/model_configs_init.sql
  aperag/migration/versions/20250722181709-8e8b89db412c.py
  aperag/schema/view_models.py
  aperag/service/collection_service.py
  aperag/service/document_service.py
  aperag/tasks/document.py
  aperag/tasks/models.py
  aperag/views/utils.py
  docs/design/vision_index_creation_zh.md
  frontend/src/api/models/collection-config.ts
  frontend/src/api/models/document.ts
  frontend/src/api/models/rebuild-indexes-request.ts
  frontend/src/api/models/reference.ts
  frontend/src/api/models/search-result-item.ts
  frontend/src/api/openapi.merged.yaml
  frontend/src/components/index.ts
  frontend/src/locales/en-US.ts
  frontend/src/locales/en-US/collection.ts
  frontend/src/locales/zh-CN.ts
  frontend/src/locales/zh-CN/collection.ts
  frontend/src/pages/bots/$botId/chats/_chat_message.tsx
  frontend/src/pages/collections/$collectionId/documents.tsx
  frontend/src/pages/collections/$collectionId/search.tsx
  frontend/src/pages/collections/_form/index.tsx
  frontend/src/pages/settings/modelConfiguration.tsx
  models/alibaba_bailian_models_completion.json
  models/alibaba_bailian_models_embedding.json
  models/generate_model_configs.py
  models/openrouter_models.json
  pyproject.toml
  tests/e2e_test/cache/test_completion_service_cache.py
  tests/unit_test/llm/images/one_dog_and_one_cat_on_the_bed.jpg
  tests/unit_test/llm/images/two_cats_on_the_purplish_red_sofa.jpg
  tests/unit_test/llm/test_image_data.py
  tests/unit_test/llm/test_multimodal_embedding.py
  tests/unit_test/llm/test_vision_llm.py
  uv.lock
Labels: size/XXL

#1163 chore: support visual description preview
  aperag/api/components/schemas/document.yaml
  aperag/flow/runners/llm.py
  aperag/index/document_parser.py
  aperag/index/vector_index.py
  aperag/index/vision_index.py
  aperag/schema/view_models.py
  aperag/service/document_service.py
  frontend/package.json
  frontend/src/api/models/document-preview.ts
  frontend/src/api/models/index.ts
  frontend/src/api/models/vision-chunk.ts
  frontend/src/api/openapi.merged.yaml
  frontend/src/components/AuthAssetImage.tsx
  frontend/src/components/ChunkViewer.tsx
  frontend/yarn.lock
Labels: size/XL

#1165 feat: support summary search
  aperag/api/components/schemas/collection.yaml
  aperag/context/context.py
  aperag/db/models.py
  aperag/db/repositories/search.py
  aperag/flow/runners/__init__.py
  aperag/flow/runners/merge.py
  aperag/flow/runners/summary_search.py
  aperag/flow/runners/vector_search.py
  aperag/index/summary_index.py
  aperag/index/vector_index.py
  aperag/migration/versions/20250728131657-b7679c9f05db.py
  aperag/schema/view_models.py
  aperag/service/collection_service.py
  aperag/vectorstore/qdrant_connector.py
  frontend/src/api/models/index.ts
  frontend/src/api/models/search-request.ts
  frontend/src/api/models/search-result-item.ts
  frontend/src/api/models/search-result.ts
  frontend/src/api/models/summary-search-params.ts
  frontend/src/api/openapi.merged.yaml
  frontend/src/locales/en-US.ts
  frontend/src/locales/zh-CN.ts
  frontend/src/pages/collections/$collectionId/search.tsx
Labels: size/XL

#1170 chore: move MinerU settings to a global place
  aperag/api/components/schemas/collection.yaml
  aperag/api/components/schemas/settings.yaml
  aperag/api/openapi.yaml
  aperag/api/paths/collections.yaml
  aperag/api/paths/misc.yaml
  aperag/api/paths/settings.yaml
  aperag/app.py
  aperag/db/models.py
  aperag/db/ops.py
  aperag/db/repositories/setting.py
  aperag/docparser/doc_parser.py
  aperag/migration/versions/20250730110318-f7671d2a7bff.py
  aperag/schema/view_models.py
  aperag/service/setting_service.py
  aperag/tasks/utils.py
  aperag/views/settings.py
  frontend/src/api/apis/default-api.ts
  frontend/src/api/models/collection-config.ts
  frontend/src/api/models/index.ts
  frontend/src/api/models/settings-test-mineru-token-post-request.ts
  frontend/src/api/models/settings-test-mineru-token-post200-response.ts
  frontend/src/api/models/settings.ts
  frontend/src/api/openapi.merged.yaml
  frontend/src/locales/en-US.ts
  frontend/src/locales/en-US/collection.ts
  frontend/src/locales/en-US/settings.ts
  frontend/src/locales/zh-CN.ts
  frontend/src/locales/zh-CN/collection.ts
  frontend/src/locales/zh-CN/settings.ts
  frontend/src/pages/collections/_form/index.tsx
  frontend/src/pages/settings/_navbar.tsx
  frontend/src/pages/settings/miscellaneous.tsx
Labels: size/XXL

#1173 feat: optimize agent message display
  aperag/agent/tool_use_message_formatters.py
  aperag/service/agent_chat_service.py
  frontend/src/pages/agent/$botId/chats/_chat_input.tsx
  frontend/src/pages/agent/$botId/chats/_chat_message.tsx
  frontend/src/pages/bots/$botId/chats/_chat_input.tsx
Labels: size/M

#1174 feat: optimize agent message display
  aperag/agent/tool_use_message_formatters.py
  aperag/service/prompt_template_service.py
  frontend/src/pages/agent/$botId/chats/_chat_message.tsx
Labels: size/XL

#1175 feat: optimize agent message display
  aperag/db/repositories/llm_provider.py
  aperag/migration/sql/model_configs_init.sql
  aperag/service/llm_available_model_service.py
  aperag/service/llm_provider_service.py
  frontend/src/components/model-select.tsx
  frontend/src/locales/en-US.ts
  frontend/src/locales/en-US/models.ts
  frontend/src/locales/zh-CN.ts
  frontend/src/locales/zh-CN/models.ts
  frontend/src/models/models.ts
  frontend/src/pages/agent/$botId/chats/_chat_input.tsx
  frontend/src/pages/bots/$botId/chats/_chat_input.tsx
  frontend/src/pages/bots/$botId/flow/_nodes/_node_llm.tsx
  frontend/src/pages/collections/_form/index.tsx
  frontend/src/pages/settings/modelConfiguration.tsx
  models/generate_model_configs.py
Labels: size/XL
