Repository apecloud/ApeRAG, pull requests merged in 2025-06, with the labels that each got.

#923 chore: add docs
  .cursorrules
  .gitignore
  aperag/docparser/README-zh.md
  aperag/docparser/README.md
  aperag/embed/base_embedding.py
  aperag/embed/local_path_embedding.py
  aperag/service/document_service.py
  aperag/source/README-zh.md
  aperag/source/README.md
  aperag/tasks/index.py
  docs/ApeRAG_Document_Processing_Flow.md
  docs/zh/ApeRAG_Document_Processing_Flow.md
Labels: size/XXL

#926 fix: lightrag error
  aperag/graph/lightrag_holder.py
Labels: size/XS

#927 chore: print response body if request failed
  tests/e2e_test/conftest.py
  tests/e2e_test/test_api_key.py
  tests/e2e_test/test_bot.py
  tests/e2e_test/test_chat.py
  tests/e2e_test/test_collection.py
  tests/e2e_test/test_document.py
  tests/e2e_test/test_user.py
Labels: size/L

#928 chore: support migration using alembic
  Makefile
  README.md
  README_zh.md
  aperag/alembic.ini
  aperag/app.py
  aperag/config.py
  aperag/db/models.py
  aperag/db/ops.py
  aperag/migration/README
  aperag/migration/env.py
  aperag/migration/script.py.mako
  aperag/migration/sql/model_configs_init.sql
  aperag/migration/utils.py
  aperag/migration/versions/20250610141055-6b261afb99c8.py
  aperag/migration/versions/20250610141215-be090f06152e.py
  aperag/migrations/0002_add_llm_provider_models.py
  aperag/migrations/0003_add_tags_field_to_llm_provider_model.py
  aperag/migrations/0004_update_llm_provider_and_model_service_provider.py
  aperag/migrations/0005_execute_model_configs_sql.py
  aperag/service/api_key_service.py
  aperag/tasks/index.py
  aperag/views/auth.py
  pyproject.toml
  uv.lock
Labels: size/XXL

#930 fix: failed e2e test cases
  aperag/version/__init__.py
  pyproject.toml
  tests/e2e_test/test_bot.py
  tests/e2e_test/test_chat.py
  tests/e2e_test/test_document.py
Labels: size/L

#933 chore: remove useless code
  aperag/templates/403.html
  aperag/templates/404.html
  aperag/templates/aperag/dashboard.html
  text.yaml
Labels: size/XL

#935 feat: Add Models
  aperag/db/ops.py
  aperag/graph/lightrag/lightrag.py
  aperag/graph/lightrag_manager.py
  aperag/migration/sql/model_configs_init.sql
  models/alibaba_bailian_models_completion.json
  models/alibaba_bailian_models_embedding.json
  models/alibaba_bailian_models_rerank.json
  models/openrouter_models.json
  scripts/generate_model_configs.py
Labels: size/XXL

#938 chore: add doc-ray deployment to the helm chart
  README.md
  README_zh.md
  deploy/aperag/templates/_helpers.tpl
  deploy/aperag/templates/aperag-secret.yaml
  deploy/aperag/templates/docray.yaml
  deploy/aperag/values.yaml
  docker-compose.yml
Labels: size/L

#942 fix: document stuck in status 'DELETING'
  aperag/db/models.py
  aperag/db/ops.py
  aperag/index/reconciler.py
  aperag/service/document_service.py
  aperag/tasks/collection.py
Labels: size/L

#944 feat: modify model config
  Makefile
  aperag/api/components/schemas/model.yaml
  aperag/api/openapi.yaml
  aperag/api/paths/llm_configuration.yaml
  aperag/api/paths/models.yaml
  aperag/db/models.py
  aperag/db/ops.py
  aperag/index/reconciler.py
  aperag/index/vector_index.py
  aperag/migration/sql/model_configs_init.sql
  aperag/migration/versions/20250616175214-172905031acc.py
  aperag/migration/versions/20250616175912-722b6fa5ec88.py
  aperag/schema/view_models.py
  aperag/service/llm_config_service.py
  aperag/service/llm_configuration_service.py
  aperag/service/model_service.py
  aperag/tasks/collection.py
  aperag/views/main.py
  aperag/views/utils.py
  frontend/src/api/apis/default-api.ts
  frontend/src/api/apis/llmapi.ts
  frontend/src/api/models/index.ts
  frontend/src/api/models/llm-provider-create-with-api-key.ts
  frontend/src/api/models/llm-provider-list.ts
  frontend/src/api/models/llm-provider-update-with-api-key.ts
  frontend/src/api/models/llm-provider.ts
  frontend/src/api/models/model-service-provider-list.ts
  frontend/src/api/models/rerank-document-document.ts
  frontend/src/api/models/rerank-document.ts
  frontend/src/api/models/rerank-request-documents-one-of-inner.ts
  frontend/src/api/models/rerank-request-documents.ts
  frontend/src/api/models/rerank-request.ts
  frontend/src/api/models/rerank-response.ts
  frontend/src/api/models/rerank-usage.ts
  frontend/src/api/openapi.merged.yaml
  frontend/src/locales/en-US/models.ts
  frontend/src/locales/zh-CN/models.ts
  frontend/src/pages/settings/_navbar.tsx
  frontend/src/pages/settings/modelConfiguration.tsx
  frontend/src/pages/settings/modelProviders.tsx
  models/generate_model_configs.py
Labels: size/XXL

#945 feat: refactor code
  aperag/db/ops.py
  aperag/flow/runners/llm.py
  aperag/flow/runners/rerank.py
  aperag/graph/lightrag_manager.py
  aperag/llm/embed/base_embedding.py
  aperag/service/bot_service.py
  aperag/service/llm_configuration_service.py
  aperag/service/model_service.py
  aperag/views/llm.py
  tests/unit_test/test_model_service.py
Labels: size/L

#947 chore: refactor db ops
  aperag/db/ops.py
  aperag/db/repositories/__init__.py
  aperag/db/repositories/api_key.py
  aperag/db/repositories/base.py
  aperag/db/repositories/bot.py
  aperag/db/repositories/chat.py
  aperag/db/repositories/collection.py
  aperag/db/repositories/document.py
  aperag/db/repositories/lightrag.py
  aperag/db/repositories/llm_provider.py
  aperag/db/repositories/search_test.py
  aperag/db/repositories/system.py
  aperag/db/repositories/user.py
  aperag/migration/versions/20250615205828-fc6cc94f112c.py
  aperag/migration/versions/20250616175214-172905031acc.py
  aperag/migration/versions/20250616175912-722b6fa5ec88.py
  aperag/migration/versions/20250617113447-dcc0b6c56552.py
  aperag/migration/versions/20250617113448-12ea6d2bf365.py
  tests/e2e_test/config.py
  tests/e2e_test/conftest.py
Labels: size/XXL

#949 feat: add evaluation
  Makefile
  aperag/evaluation/.gitignore
  aperag/evaluation/README-zh.md
  aperag/evaluation/README.md
  aperag/evaluation/__init__.py
  aperag/evaluation/config.example.yaml
  aperag/evaluation/run.py
  evaluation/threekingdoms/datasets/qa.csv
  tests/e2e_test/evaluation/eval.py
  tests/e2e_test/evaluation/ragas.png
Labels: size/XXL

#951 feat: add business error code and optimize exception handler
  aperag/api/paths/bots.yaml
  aperag/api/paths/chats.yaml
  aperag/app.py
  aperag/db/models.py
  aperag/db/repositories/bot.py
  aperag/db/repositories/chat.py
  aperag/db/repositories/collection.py
  aperag/db/repositories/lightrag.py
  aperag/db/repositories/llm_provider.py
  aperag/exception_handlers.py
  aperag/exceptions.py
  aperag/flow/engine.py
  aperag/service/api_key_service.py
  aperag/service/bot_service.py
  aperag/service/chat_service.py
  aperag/service/collection_service.py
  aperag/service/document_service.py
  aperag/service/flow_service.py
  aperag/service/llm_available_model_service.py
  aperag/service/llm_provider_service.py
  aperag/service/prompt_template_service.py
  aperag/tasks/collection.py
  aperag/utils/utils.py
  aperag/views/api_key.py
  aperag/views/auth.py
  aperag/views/config.py
  aperag/views/main.py
  aperag/views/utils.py
Labels: size/XXL

#952 feat: fix db query
  aperag/db/repositories/bot.py
  aperag/db/repositories/chat.py
  aperag/db/repositories/collection.py
  aperag/db/repositories/document.py
  aperag/db/repositories/llm_provider.py
  aperag/views/main.py
Labels: size/L

#953 Revert "feat: fix db query"
  aperag/db/repositories/bot.py
  aperag/db/repositories/chat.py
  aperag/db/repositories/collection.py
  aperag/db/repositories/document.py
  aperag/db/repositories/llm_provider.py
  aperag/views/main.py
Labels: size/L

#954 Feature/fix index2
  aperag/concurrent_control/README-MultiLock.md
  aperag/concurrent_control/__init__.py
  aperag/concurrent_control/core.py
  aperag/db/repositories/collection.py
  aperag/db/repositories/document.py
  aperag/graph/lightrag/lightrag.py
  aperag/graph/lightrag/operate.py
  aperag/graph/lightrag/utils.py
  aperag/graph/lightrag/utils_graph.py
  aperag/views/main.py
  config/celery.py
  docs/technical_designs/Connected_Components_Optimization.md
  docs/technical_designs/Graph_Indexing_Concurrency_Optimization.md
  docs/technical_designs/LightRAG_Entity_Extraction_and_Merging.md
  tests/unit_test/concurrent_control/test_multilock.py
  tests/unit_test/test_lightrag_connected_components.py
Labels: size/XXL

#957 feat: fix feedback bug
  aperag/db/repositories/chat.py
  aperag/service/chat_service.py
Labels: size/L

#958 fix: concurrent index reconciling
  aperag/db/repositories/collection.py
  aperag/db/repositories/document.py
  aperag/exceptions.py
  aperag/index/reconciler.py
  aperag/llm/embed/base_embedding.py
  aperag/tasks/collection.py
  aperag/tasks/document.py
  aperag/tasks/utils.py
Labels: size/L

#960 feat: remove useless code
  aperag/graph/lightrag/kg/__init__.py
  aperag/graph/lightrag/kg/postgres_sync_impl.py
  aperag/graph/lightrag/lightrag.py
  aperag/graph/lightrag_manager.py
  aperag/service/llm_available_model_service.py
  deploy/aperag/templates/aperag-secret.yaml
  deploy/aperag/values.yaml
  envs/env.template
  tests/unit_test/test_model_service.py
Labels: size/XL

#966 feat: refine query context
  aperag/flow/runners/graph_search.py
  aperag/graph/lightrag/context_types.py
  aperag/graph/lightrag/lightrag.py
  aperag/graph/lightrag/operate.py
Labels: size/L

#964 chore: optimize index task callbacks
  aperag/db/models.py
  aperag/index/reconciler.py
  docs/indexing_architecture.md
  docs/indexing_architecture_zh.md
Labels: size/L

#967 feat: enable late task acknowledgment in Celery configuration
  config/celery.py
Labels: size/XS

#968 Feature: speed up graph index
  aperag/graph/lightrag/constants.py
  aperag/graph/lightrag/lightrag.py
  aperag/graph/lightrag/operate.py
  aperag/graph/lightrag_manager.py
  aperag/index/reconciler.py
  tests/unit_test/graphindex/test_lightrag_context_types.py
  tests/unit_test/graphindex/test_lightrag_refactor.py
  tests/unit_test/test_lightrag_connected_components.py
Labels: size/XXL

#974 feat: support concurrent_control
  aperag/concurrent_control/README-MultiLock.md
  aperag/concurrent_control/README-zh.md
  aperag/concurrent_control/README.md
  aperag/concurrent_control/__init__.py
  aperag/concurrent_control/core.py
  aperag/concurrent_control/manager.py
  aperag/concurrent_control/protocols.py
  aperag/concurrent_control/redis_lock.py
  aperag/concurrent_control/threading_lock.py
  aperag/concurrent_control/utils.py
  aperag/db/redis_manager.py
  tests/unit_test/concurrent_control/test_lock_manager.py
  tests/unit_test/concurrent_control/test_multilock.py
  tests/unit_test/concurrent_control/test_redis_lock.py
  tests/unit_test/concurrent_control/test_thread_safety.py
  tests/unit_test/concurrent_control/test_utilities.py
Labels: size/XXL

#975 refactor: rename document_indexes to document_index and update relate…
  aperag/db/models.py
  aperag/migration/versions/20250617113447-dcc0b6c56552.py
  frontend/src/locales/en-US.ts
  frontend/src/locales/zh-CN.ts
  frontend/src/pages/collections/$collectionId/documents.tsx
Labels: size/L

#985 feat: update document index status model and related components
  aperag/api/components/schemas/document.yaml
  aperag/api/paths/collections.yaml
  aperag/db/models.py
  aperag/index/manager.py
  aperag/index/reconciler.py
  aperag/migration/versions/20250624132425-850b2c5dc08f.py
  aperag/migration/versions/20250624132601-66b96592c84a.py
  aperag/schema/view_models.py
  aperag/service/document_service.py
  aperag/tasks/scheduler.py
  aperag/utils/constant.py
  aperag/views/main.py
  config/celery_tasks.py
  docs/indexing_architecture.md
  docs/indexing_architecture_zh.md
  frontend/src/api/apis/default-api.ts
  frontend/src/api/models/document-update.ts
  frontend/src/api/models/document.ts
  frontend/src/api/models/index.ts
  frontend/src/api/openapi.merged.yaml
  frontend/src/constants/index.ts
  frontend/src/locales/en-US.ts
  frontend/src/locales/zh-CN.ts
  tests/e2e_test/conftest.py
  tests/e2e_test/test_document.py
Labels: size/XXL

#990 feat: rechunker should not rely on object types
  aperag/docparser/chunking.py
Labels: size/S

#991 feat: mark document as deleted instead of removing from database
  aperag/service/document_service.py
Labels: size/XS

#989 Feature/refine prompt
  aperag/graph/lightrag_manager.py
  aperag/llm/prompts.py
  aperag/migration/sql/model_configs_init.sql
  aperag/schema/view_models.py
  models/generate_model_configs.py
Labels: size/M

#993 feat: enhance model name handling in API and documentation
  aperag/api/paths/llm_configuration.yaml
  aperag/schema/view_models.py
  aperag/service/llm_provider_service.py
  aperag/views/main.py
  frontend/src/api/apis/default-api.ts
  frontend/src/api/models/audit-log.ts
  frontend/src/api/openapi.merged.yaml
  tests/e2e_test/test_llm_provider.py
Labels: size/L

#996 feat: update session cookie management and JWT expiration
  aperag/views/auth.py
Labels: size/XS

#997 refactor: remove max_tokens parameter from LLM configurations and upd…
  aperag/flow/examples/rag_flow.yaml
  aperag/flow/examples/rag_flow2.yaml
  aperag/flow/runners/llm.py
  aperag/llm/completion/completion_service.py
  frontend/src/locales/en-US.ts
  frontend/src/locales/zh-CN.ts
  frontend/src/pages/bots/$botId/flow/_nodes/_node_llm.tsx
  frontend/src/pages/bots/$botId/flow/utils.ts
  tests/e2e_test/testdata/basic-flow.yaml
  tests/e2e_test/testdata/rag-flow.yaml
  tests/model_test/basic-flow.yaml
Labels: size/L
