Repository apecloud/ApeRAG, pull requests merged in 2025-09, with the labels that each got.

#1277 feat: replace image
  README-zh.md
  README.md
  aperag/context/context.py
  aperag/db/repositories/collection.py
  aperag/flow/base/models.py
  aperag/flow/runners/fulltext_search.py
  aperag/flow/runners/vector_search.py
  aperag/index/fulltext_index.py
  aperag/mcp/server.py
  aperag/schema/view_models.py
  aperag/service/chat_collection_service.py
  aperag/service/chat_document_service.py
  aperag/service/chat_service.py
  aperag/service/collection_service.py
  aperag/service/prompt_template_service.py
  aperag/tasks/utils.py
  aperag/views/chat_documents.py
  aperag/views/main.py
  docs/images/HarryPotterKG.png
  web/docs/about-aperag.mdx
Labels: size/L

#1282 fix: docs i18n
  web/docs/databases/readme.mdx
  web/docs/documents/build-docker-image-zh.mdx
  web/docs/documents/build-docker-image.mdx
  web/docs/documents/design/indexing_architecture.mdx
  web/docs/documents/design/indexing_architecture_zh.mdx
  web/docs/documents/design/lightrag_entity_extraction_and_merging.mdx
  web/docs/documents/design/lightrag_entity_extraction_and_merging_zh.mdx
  web/docs/documents/design/quota-system-design-zh.mdx
  web/docs/documents/design/quota-system-design.mdx
  web/docs/documents/design/vision_index_creation_zh.mdx
  web/docs/documents/design/web-search-design-zh.mdx
  web/docs/documents/jaeger-tracing.mdx
  web/docs/documents/references/how-to-debug.mdx
  web/docs/en-US/about-aperag.md
  web/docs/en-US/design/_category.yaml
  web/docs/en-US/design/authentication.md
  web/docs/en-US/design/function/_category.yaml
  web/docs/en-US/design/function/connected_components_optimization.md
  web/docs/en-US/design/function/graph_index_creation.md
  web/docs/en-US/development/_category.yaml
  web/docs/en-US/development/build-docker-image.md
  web/docs/en-US/development/development-guide.md
  web/docs/zh-CN/about-aperag.md
  web/docs/zh-CN/design/_category.yaml
  web/docs/zh-CN/design/authentication.md
  web/docs/zh-CN/design/function/_category.yaml
  web/docs/zh-CN/design/function/agent-backend.md
  web/docs/zh-CN/design/function/collection_marketplace_design.md
  web/docs/zh-CN/design/function/connected_components_optimization.md
  web/docs/zh-CN/design/function/evaluation-design.md
  web/docs/zh-CN/design/function/graph_index_creation.md
  web/docs/zh-CN/development/_category.yaml
  web/docs/zh-CN/development/build-docker-image.md
  web/docs/zh-CN/development/development-guide.md
  web/package.json
  web/public/docs/images/HarryPotterKG2.png
  web/public/docs/images/chat2.png
  web/src/app/docs/[group]/[[...paths]]/page.tsx
  web/src/app/docs/docs-sidebar.tsx
  web/src/app/docs/layout.tsx
  web/src/app/docs/not-found.tsx
  web/src/app/docs/page.tsx
  web/src/components/app-topbar.tsx
  web/src/components/page-container.tsx
  web/src/i18n/en-US.json
  web/src/i18n/en-US/page_docs.json
  web/src/i18n/zh-CN.json
  web/src/i18n/zh-CN/page_docs.json
  web/src/lib/docs.ts
  web/src/services/cookies.ts
  web/yarn.lock
Labels: size/XXL

#1286 feat: allow unauthenticated access to marketplace for better user exp…
  aperag/service/document_service.py
  aperag/service/marketplace_service.py
  aperag/views/auth.py
  aperag/views/collections.py
  aperag/views/marketplace.py
Labels: size/L

#1291 fix: marketplace authentication
  aperag/service/collection_service.py
  aperag/service/document_service.py
  aperag/views/api_key.py
  aperag/views/audit.py
  aperag/views/auth.py
  aperag/views/chat_completion.py
  aperag/views/chat_documents.py
  aperag/views/collections.py
  aperag/views/evaluation.py
  aperag/views/flow.py
  aperag/views/graph.py
  aperag/views/llm.py
  aperag/views/main.py
  aperag/views/marketplace.py
  aperag/views/marketplace_collections.py
  aperag/views/quota.py
  aperag/views/settings.py
  aperag/views/web.py
Labels: size/L

#1295 fix: indexing reload
  web/src/app/workspace/agents/[botId]/chats/[chatId]/chat-input.tsx
Labels: size/XS

#1297 fix: files is missing in chat message
  aperag/api/components/schemas/agent.yaml
  aperag/api/components/schemas/chat.yaml
  aperag/chat/history/message.py
  aperag/schema/view_models.py
  aperag/service/agent_chat_service.py
Labels: size/M

#1300 fix: ignore duplicate documents check in chat collection
  aperag/service/chat_document_service.py
  aperag/service/document_service.py
Labels: size/XS

#1313 fix: chat no response
  aperag/service/agent_chat_service.py
Labels: size/S

#1316 fix: bot default collections not work
  aperag/service/bot_service.py
  aperag/service/prompt_template_service.py
Labels: size/M

#1317 fix: bot update
  web/src/app/bots/[botId]/bot-settings.tsx
  web/src/app/bots/[botId]/layout.tsx
  web/src/app/bots/[botId]/page.tsx
  web/src/app/bots/bot-form.tsx
  web/src/components/providers/bot-provider.tsx
Labels: size/L

#1322 chore: separate vision search from vector search
  aperag/api/components/schemas/collection.yaml
  aperag/app.py
  aperag/db/models.py
  aperag/db/repositories/bot.py
  aperag/db/repositories/search.py
  aperag/flow/runners/__init__.py
  aperag/flow/runners/merge.py
  aperag/flow/runners/vector_search.py
  aperag/flow/runners/vision_search.py
  aperag/index/vision_index.py
  aperag/mcp/server.py
  aperag/migration/versions/20250905212643-d112e0332219.py
  aperag/schema/view_models.py
  aperag/service/agent_chat_service.py
  aperag/service/bot_service.py
  aperag/service/chat_document_service.py
  aperag/service/collection_service.py
  aperag/service/document_service.py
  aperag/service/prompt_template_service.py
  aperag/views/bot.py
  aperag/views/chat.py
  aperag/views/chat_documents.py
  aperag/views/collections.py
  aperag/views/marketplace_collections.py
  aperag/views/openai.py
  aperag/views/utils.py
  web/src/api/models/index.ts
  web/src/api/models/search-request.ts
  web/src/api/models/search-result-item.ts
  web/src/api/models/search-result.ts
  web/src/api/models/vision-search-params.ts
  web/src/api/openapi.merged.yaml
Labels: size/XL

#1324 Support/anybase
  aperag/source/anybase.py
Labels: size/XS

#1327 fix: generate title failed
  aperag/api/components/schemas/model.yaml
  aperag/schema/view_models.py
  aperag/service/default_model_service.py
Labels: size/S

#1330 feat: add feishu
  README-zh.md
  README.md
  aperag/schema/view_models.py
  aperag/service/default_model_service.py
  docs/images/feishu-qr-code.png
Labels: size/S

#1331 Support/anybase
  aperag/views/auth.py
Labels: size/S

#1339 fix: pm2-runtime
  web/Dockerfile
Labels: size/XS

#1342 Support/anybase
  aperag/tasks/collection.py
Labels: size/S

#1361 fix: graph fullscreen
  web/package.json
  web/src/app/workspace/collections/[collectionId]/graph/collection-graph.tsx
  web/src/components/ui/command.tsx
  web/src/i18n/en-US.json
  web/src/i18n/en-US/page_graph.json
  web/src/i18n/zh-CN.json
  web/src/i18n/zh-CN/page_graph.json
  web/yarn.lock
Labels: size/XL

#1362 fix: install the ik-analyzer plugin before starting ES
  scripts/init-es.sh
Labels: size/M

#1364 fix: upload with simulation
  web/src/app/workspace/collections/[collectionId]/documents/upload/document-upload.tsx
Labels: size/L

#1380 fix: parsing MinerU result of VLM backend
  aperag/docparser/mineru_common.py
Labels: size/M
