Repository apecloud/ApeRAG, pull requests merged in 2025-08, with the labels that each got.

#1195 fix: tag filters
  frontend/src/components/model-select.tsx
  frontend/src/models/models.ts
  frontend/src/pages/agent/$botId/chats/_chat_input.tsx
  frontend/src/pages/bots/$botId/chats/_chat_input.tsx
  frontend/src/pages/bots/$botId/flow/_nodes/_node_llm.tsx
  frontend/src/pages/collections/_form/index.tsx
Labels: size/M

#1200 feat: use default rerank
  aperag/flow/runners/rerank.py
  aperag/mcp/server.py
  aperag/service/collection_service.py
  aperag/service/default_model_service.py
  frontend/src/pages/collections/$collectionId/search.tsx
Labels: size/L

#1193 feat: quota enhcancement
  aperag/api/components/schemas/quota.yaml
  aperag/api/openapi.yaml
  aperag/api/paths/quotas.yaml
  aperag/db/models.py
  aperag/db/repositories/user.py
  aperag/exceptions.py
  aperag/migration/versions/20250805104914-5b7f5b4b3765.py
  aperag/schema/view_models.py
  aperag/service/bot_service.py
  aperag/service/collection_service.py
  aperag/service/document_service.py
  aperag/service/quota_service.py
  aperag/utils/constant.py
  aperag/views/auth.py
  aperag/views/main.py
  aperag/views/quota.py
  docs/design/quota-system-design-zh.md
  docs/design/quota-system-design.md
  frontend/openapitools.json
  frontend/src/api/api.ts
  frontend/src/api/apis/quotas-api.ts
  frontend/src/api/models/index.ts
  frontend/src/api/models/quota-info.ts
  frontend/src/api/models/quota-update-request.ts
  frontend/src/api/models/quota-update-response-updated-quotas-inner.ts
  frontend/src/api/models/quota-update-response.ts
  frontend/src/api/models/quotas-get200-response.ts
  frontend/src/api/models/quotas-user-id-recalculate-post200-response.ts
  frontend/src/api/models/system-default-quotas-response.ts
  frontend/src/api/models/system-default-quotas-update-request.ts
  frontend/src/api/models/system-default-quotas-update-response.ts
  frontend/src/api/models/system-default-quotas.ts
  frontend/src/api/models/user-quota-info.ts
  frontend/src/api/models/user-quota-list.ts
  frontend/src/api/openapi.merged.yaml
  frontend/src/locales/en-US.ts
  frontend/src/locales/zh-CN.ts
  frontend/src/models/user.ts
  frontend/src/pages/settings/_navbar.tsx
  frontend/src/pages/settings/quotas.tsx
  frontend/src/services/index.ts
Labels: size/XXL

#1205 feat: update prompt
  aperag/service/prompt_template_service.py
Labels: size/M

#1207 chore: optimize summary index prompt and enable full text search by default
  aperag/mcp/server.py
  aperag/service/collection_service.py
Labels: size/M

#1212 chore: web search
  frontend/src/assets/web_search.svg
  frontend/src/pages/agent/$botId/chats/_chat_input.tsx
Labels: size/M

#1219 fix: username conflict
  aperag/views/auth.py
Labels: size/XS

#1229 fix: database session attached to a different event loop
  aperag/service/collection_service.py
  aperag/service/collection_summary_service.py
  config/celery_tasks.py
  frontend/src/locales/zh-CN/collection.ts
  frontend/src/pages/collections/_form/index.tsx
Labels: size/L

#1232 fix: search user quota failed
  aperag/service/quota_service.py
Labels: size/XS

#1248 chore: upgrade mcp-agent to 0.1.13
  pyproject.toml
  uv.lock
Labels: size/M

#1249 fix: feedback failed
  aperag/chat/history/message.py
  aperag/db/models.py
  aperag/db/repositories/chat.py
  aperag/migration/versions/20250825112501-6622089995c7.py
  aperag/service/chat_service.py
  aperag/utils/history.py
Labels: size/M

#1250 chore: upgrade litellm for jina multimodal embedding api
  aperag/chat/history/message.py
  aperag/llm/embed/embedding_service.py
  pyproject.toml
  uv.lock
Labels: size/M

#1252 feat: generate a knowledge graph for the answer
  aperag/service/prompt_template_service.py
Labels: size/M

#1263 fix: evaluation update
  web/src/api/apis/default-api.ts
  web/src/api/openapi.merged.yaml
  web/src/app/workspace/collections/[collectionId]/collection-header.tsx
  web/src/app/workspace/collections/[collectionId]/graph/collection-graph.tsx
  web/src/app/workspace/collections/[collectionId]/graph/page.tsx
  web/src/app/workspace/evaluations/[evaluationId]/evaluation-result.tsx
  web/src/app/workspace/evaluations/[evaluationId]/evaluation-retry-item.tsx
  web/src/app/workspace/evaluations/[evaluationId]/page.tsx
  web/src/app/workspace/market/collections/[collectionId]/collection-header.tsx
  web/src/app/workspace/market/collections/[collectionId]/documents/[documentId]/document-detail.tsx
  web/src/app/workspace/market/collections/[collectionId]/graph/page.tsx
Labels: size/XL

#1264 fix: collection header
  web/src/app/workspace/collections/[collectionId]/collection-header.tsx
  web/src/app/workspace/collections/collection-list.tsx
  web/src/app/workspace/market/collections/[collectionId]/collection-header.tsx
  web/src/app/workspace/market/collections/collection-list.tsx
Labels: size/M

#1267 fix: graph zoom
  web/package.json
  web/src/components/chart-mermaid.tsx
  web/src/components/markdown.tsx
  web/yarn.lock
Labels: size/M

#1269 chore: optimize collection summary size
  aperag/service/collection_summary_service.py
Labels: size/S

#1271 Bugfix/frontend
  web/.gitignore
  web/src/i18n/en-US.d.json.ts
Labels: size/S

#1247 feat: Implement In-Chat Document Upload for Temporary Knowledge Augmentation
  aperag/agent/i18n.py
  aperag/agent/tool_reference_extractor.py
  aperag/agent/tool_use_message_formatters.py
  aperag/api/components/schemas/document.yaml
  aperag/api/openapi.yaml
  aperag/api/paths/chat_documents.yaml
  aperag/app.py
  aperag/chat/history/message.py
  aperag/context/context.py
  aperag/db/models.py
  aperag/db/repositories/collection.py
  aperag/flow/base/models.py
  aperag/flow/runners/fulltext_search.py
  aperag/flow/runners/vector_search.py
  aperag/index/fulltext_index.py
  aperag/mcp/server.py
  aperag/migration/versions/20250829101722-624ebebacb56.py
  aperag/schema/view_models.py
  aperag/service/agent_chat_service.py
  aperag/service/chat_collection_service.py
  aperag/service/chat_document_service.py
  aperag/service/chat_service.py
  aperag/service/collection_service.py
  aperag/service/document_service.py
  aperag/service/marketplace_collection_service.py
  aperag/service/marketplace_service.py
  aperag/service/prompt_template_service.py
  aperag/tasks/utils.py
  aperag/utils/history.py
  aperag/views/auth.py
  aperag/views/chat_documents.py
  aperag/views/main.py
Labels: size/XXL

#1274 fix: i18n in settings
  web/src/app/docs/layout.tsx
  web/src/app/workspace/api-keys/api-key-actions.tsx
  web/src/app/workspace/api-keys/api-key-table.tsx
  web/src/app/workspace/api-keys/page.tsx
  web/src/app/workspace/audit-logs/audit-log-table.tsx
  web/src/app/workspace/audit-logs/page.tsx
  web/src/app/workspace/quotas/page.tsx
  web/src/app/workspace/quotas/quota-radial-chart.tsx
  web/src/components/app-topbar.tsx
  web/src/components/date-time-picker-24h.tsx
  web/src/i18n/en-US.json
  web/src/i18n/en-US/components.json
  web/src/i18n/en-US/page_api_keys.json
  web/src/i18n/en-US/page_audit_logs.json
  web/src/i18n/en-US/page_auth.json
  web/src/i18n/en-US/page_quota.json
  web/src/i18n/zh-CN.json
  web/src/i18n/zh-CN/components.json
  web/src/i18n/zh-CN/page_api_keys.json
  web/src/i18n/zh-CN/page_audit_logs.json
  web/src/i18n/zh-CN/page_auth.json
  web/src/i18n/zh-CN/page_quota.json
Labels: size/XL
